### ISSUE TITLE
Cannot find module 'es3ify'

### ISSUE THREAD

**Issue by RichardLitt** [BeagleLab/beagle#161]
I am continually running into an issue when running `gulp` where this happens: 

```sh
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Cannot find module 'es3ify' from '/Users/richard/src/beagle/node_modules/beagle-pdf'
    at /Users/richard/src/beagle/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/Users/richard/src/beagle/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/richard/src/beagle/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/richard/src/beagle/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/richard/src/beagle/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/richard/src/beagle/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:99:15)
```

A rerun of gulp always fixes it, which is confusing. It also happens for `beagle-style`.

**Comment by RichardLitt** [comment]
Commented on what seems a likely issue, here: https://github.com/pouchdb/pouchdb/issues/3533
