### ISSUE TITLE
Precommit hook uses system iojs, not nvm v0.12

### ISSUE THREAD

**Issue by RichardLitt** [BeagleLab/beagle#95]
Error:

```sh
/Users/richard/src/beagle/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22
    throw new Error('`libsass` bindings not found. Try reinstalling `node-sass
          ^
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/Users/richard/src/beagle/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/Users/richard/src/beagle/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:444:26)
    at Object.Module._extensions..js (module.js:462:10)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
    at Module.require (module.js:349:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/Users/richard/src/beagle/node_modules/gulp-sass/index.js:3:17)
    at Module._compile (module.js:444:26)
```

**Comment by RichardLitt** [comment]
Opened an issue in nvm here: https://github.com/creationix/nvm/issues/688
